const PYTHON: LangApiConfig = LangApiConfig {
    check_nodes: &["decorator", "call"],
    fn_scope: &["function_definition"],
    class_scope: &["class_definition"],
    base_path_markers: &[],
    patterns: &[
        // Server: Flask/FastAPI/Sanic decorator patterns
        ApiPattern::server_on(".route(", None, &["decorator"]),
        ApiPattern::server_on(".get(", Some("GET"), &["decorator"]),
        ApiPattern::server_on(".post(", Some("POST"), &["decorator"]),
        ApiPattern::server_on(".put(", Some("PUT"), &["decorator"]),
        ApiPattern::server_on(".delete(", Some("DELETE"), &["decorator"]),
        ApiPattern::server_on(".patch(", Some("PATCH"), &["decorator"]),
        ApiPattern::server_on(".head(", Some("HEAD"), &["decorator"]),
        // Client: requests, httpx, aiohttp, etc.
        ApiPattern::client_on("requests.get(", Some("GET"), &["call"]),
        ApiPattern::client_on("requests.post(", Some("POST"), &["call"]),
        ApiPattern::client_on("requests.put(", Some("PUT"), &["call"]),
        ApiPattern::client_on("requests.delete(", Some("DELETE"), &["call"]),
        ApiPattern::client_on("requests.patch(", Some("PATCH"), &["call"]),
        ApiPattern::client_on("httpx.get(", Some("GET"), &["call"]),
        ApiPattern::client_on("httpx.post(", Some("POST"), &["call"]),
        ApiPattern::client_on("httpx.put(", Some("PUT"), &["call"]),
        ApiPattern::client_on("httpx.delete(", Some("DELETE"), &["call"]),
        ApiPattern::client_on("httpx.patch(", Some("PATCH"), &["call"]),
        ApiPattern::client_on("session.get(", Some("GET"), &["call"]),
        ApiPattern::client_on("session.post(", Some("POST"), &["call"]),
        ApiPattern::client_on("client.get(", Some("GET"), &["call"]),
        ApiPattern::client_on("client.post(", Some("POST"), &["call"]),
    ],
};

const JAVASCRIPT: LangApiConfig = LangApiConfig {
    check_nodes: &["call_expression"],
    fn_scope: &[
        "function_declaration",
        "method_definition",
        "variable_declarator",
    ],
    class_scope: &["class_declaration"],
    base_path_markers: &[],
    patterns: &[
        // Client: fetch, axios, etc.
        ApiPattern::client("fetch(", None),
        ApiPattern::client("axios.get(", Some("GET")),
        ApiPattern::client("axios.post(", Some("POST")),
        ApiPattern::client("axios.put(", Some("PUT")),
        ApiPattern::client("axios.delete(", Some("DELETE")),
        ApiPattern::client("axios.patch(", Some("PATCH")),
        ApiPattern::client("http.get(", Some("GET")),
        ApiPattern::client("http.post(", Some("POST")),
        ApiPattern::client("api.get(", Some("GET")),
        ApiPattern::client("api.post(", Some("POST")),
        ApiPattern::client("ky.get(", Some("GET")),
        ApiPattern::client("ky.post(", Some("POST")),
        ApiPattern::client("got.get(", Some("GET")),
        ApiPattern::client("got.post(", Some("POST")),
        ApiPattern::client("client.get(", Some("GET")),
        ApiPattern::client("client.post(", Some("POST")),
        ApiPattern::client("request.get(", Some("GET")),
        ApiPattern::client("request.post(", Some("POST")),
        // Server: Express/Fastify/Hono/Koa (backend files only)
        ApiPattern::server_backend("app.get(", Some("GET")),
        ApiPattern::server_backend("app.post(", Some("POST")),
        ApiPattern::server_backend("app.put(", Some("PUT")),
        ApiPattern::server_backend("app.delete(", Some("DELETE")),
        ApiPattern::server_backend("app.patch(", Some("PATCH")),
        ApiPattern::server_backend("app.all(", None),
        ApiPattern::server_backend("app.use(", None),
        ApiPattern::server_backend("app.route(", None),
        ApiPattern::server_backend("router.get(", Some("GET")),
        ApiPattern::server_backend("router.post(", Some("POST")),
        ApiPattern::server_backend("router.put(", Some("PUT")),
        ApiPattern::server_backend("router.delete(", Some("DELETE")),
        ApiPattern::server_backend("router.patch(", Some("PATCH")),
        ApiPattern::server_backend("server.get(", Some("GET")),
        ApiPattern::server_backend("server.post(", Some("POST")),
        ApiPattern::server_backend("express.get(", Some("GET")),
        ApiPattern::server_backend("fastify.get(", Some("GET")),
        ApiPattern::server_backend("fastify.post(", Some("POST")),
        ApiPattern::server_backend("hono.get(", Some("GET")),
        ApiPattern::server_backend("hono.post(", Some("POST")),
    ],
};

const GO: LangApiConfig = LangApiConfig {
    check_nodes: &["call_expression"],
    fn_scope: &["function_declaration"],
    class_scope: &[],
    base_path_markers: &[],
    patterns: &[
        // Client: stdlib + libraries (check BEFORE server to avoid ambiguity)
        ApiPattern::client("http.Get(", Some("GET")),
        ApiPattern::client("http.Post(", Some("POST")),
        ApiPattern::client("http.Head(", Some("HEAD")),
        ApiPattern::client("http.PostForm(", Some("POST")),
        ApiPattern::client("http.NewRequest(", None),
        ApiPattern::client("client.Get(", Some("GET")),
        ApiPattern::client("client.Post(", Some("POST")),
        ApiPattern::client("client.Put(", Some("PUT")),
        ApiPattern::client("client.Delete(", Some("DELETE")),
        // Server: Gin/Echo (ALL-CAPS methods)
        ApiPattern::server(".GET(", Some("GET")),
        ApiPattern::server(".POST(", Some("POST")),
        ApiPattern::server(".PUT(", Some("PUT")),
        ApiPattern::server(".DELETE(", Some("DELETE")),
        ApiPattern::server(".PATCH(", Some("PATCH")),
        ApiPattern::server(".HEAD(", Some("HEAD")),
        ApiPattern::server(".OPTIONS(", Some("OPTIONS")),
        ApiPattern::server(".ANY(", None),
        // Server: Chi/Fiber (PascalCase) — client patterns already matched above
        ApiPattern::server(".Get(", Some("GET")),
        ApiPattern::server(".Post(", Some("POST")),
        ApiPattern::server(".Put(", Some("PUT")),
        ApiPattern::server(".Delete(", Some("DELETE")),
        ApiPattern::server(".Patch(", Some("PATCH")),
        ApiPattern::server("HandleFunc(", Some("GET")),
        ApiPattern::server(".Handle(", None),
    ],
};

const JAVA: LangApiConfig = LangApiConfig {
    check_nodes: &["annotation", "marker_annotation", "method_invocation"],
    fn_scope: &["method_declaration"],
    class_scope: &["class_declaration"],
    base_path_markers: &["RequestMapping"],
    patterns: &[
        // Server: Spring annotations
        ApiPattern::server_on(
            "GetMapping",
            Some("GET"),
            &["annotation", "marker_annotation"],
        ),
        ApiPattern::server_on(
            "PostMapping",
            Some("POST"),
            &["annotation", "marker_annotation"],
        ),
        ApiPattern::server_on(
            "PutMapping",
            Some("PUT"),
            &["annotation", "marker_annotation"],
        ),
        ApiPattern::server_on(
            "DeleteMapping",
            Some("DELETE"),
            &["annotation", "marker_annotation"],
        ),
        ApiPattern::server_on(
            "PatchMapping",
            Some("PATCH"),
            &["annotation", "marker_annotation"],
        ),
        ApiPattern::server_on("RequestMapping", None, &["annotation", "marker_annotation"]),
        // Client: RestTemplate, WebClient
        ApiPattern::client_on("getForObject(", Some("GET"), &["method_invocation"]),
        ApiPattern::client_on("getForEntity(", Some("GET"), &["method_invocation"]),
        ApiPattern::client_on("postForObject(", Some("POST"), &["method_invocation"]),
        ApiPattern::client_on("postForEntity(", Some("POST"), &["method_invocation"]),
        ApiPattern::client_on("exchange(", None, &["method_invocation"]),
        ApiPattern::client_on("patchForObject(", Some("PATCH"), &["method_invocation"]),
    ],
};

